// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/eidng8/go-attr-rbac/ent/accesstoken"
	"github.com/eidng8/go-attr-rbac/ent/user"
)

// Stores revoked access tokens
type AccessToken struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uint64 `json:"user_id,omitempty"`
	// AccessToken holds the value of the "access_token" field.
	AccessToken []byte `json:"-"`
	// RefreshToken holds the value of the "refresh_token" field.
	RefreshToken []byte `json:"-"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccessTokenQuery when eager-loading is set.
	Edges               AccessTokenEdges `json:"-"`
	user_access_tokens  *uint64
	user_refresh_tokens *uint64
	selectValues        sql.SelectValues
}

// AccessTokenEdges holds the relations/edges for other nodes in the graph.
type AccessTokenEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccessTokenEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccessToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accesstoken.FieldAccessToken, accesstoken.FieldRefreshToken:
			values[i] = new([]byte)
		case accesstoken.FieldID, accesstoken.FieldUserID:
			values[i] = new(sql.NullInt64)
		case accesstoken.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case accesstoken.ForeignKeys[0]: // user_access_tokens
			values[i] = new(sql.NullInt64)
		case accesstoken.ForeignKeys[1]: // user_refresh_tokens
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccessToken fields.
func (at *AccessToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accesstoken.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			at.ID = uint64(value.Int64)
		case accesstoken.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				at.UserID = uint64(value.Int64)
			}
		case accesstoken.FieldAccessToken:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field access_token", values[i])
			} else if value != nil {
				at.AccessToken = *value
			}
		case accesstoken.FieldRefreshToken:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token", values[i])
			} else if value != nil {
				at.RefreshToken = *value
			}
		case accesstoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				at.CreatedAt = new(time.Time)
				*at.CreatedAt = value.Time
			}
		case accesstoken.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_access_tokens", value)
			} else if value.Valid {
				at.user_access_tokens = new(uint64)
				*at.user_access_tokens = uint64(value.Int64)
			}
		case accesstoken.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_refresh_tokens", value)
			} else if value.Valid {
				at.user_refresh_tokens = new(uint64)
				*at.user_refresh_tokens = uint64(value.Int64)
			}
		default:
			at.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccessToken.
// This includes values selected through modifiers, order, etc.
func (at *AccessToken) Value(name string) (ent.Value, error) {
	return at.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the AccessToken entity.
func (at *AccessToken) QueryOwner() *UserQuery {
	return NewAccessTokenClient(at.config).QueryOwner(at)
}

// Update returns a builder for updating this AccessToken.
// Note that you need to call AccessToken.Unwrap() before calling this method if this AccessToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (at *AccessToken) Update() *AccessTokenUpdateOne {
	return NewAccessTokenClient(at.config).UpdateOne(at)
}

// Unwrap unwraps the AccessToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (at *AccessToken) Unwrap() *AccessToken {
	_tx, ok := at.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccessToken is not a transactional entity")
	}
	at.config.driver = _tx.drv
	return at
}

// String implements the fmt.Stringer.
func (at *AccessToken) String() string {
	var builder strings.Builder
	builder.WriteString("AccessToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", at.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", at.UserID))
	builder.WriteString(", ")
	builder.WriteString("access_token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("refresh_token=<sensitive>")
	builder.WriteString(", ")
	if v := at.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PluckAccessTokenID returns the "ID" field value.
func PluckAccessTokenID(at *AccessToken) uint64 {
	return at.ID
}

// PluckAccessTokenUserID returns the "user_id" field value.
func PluckAccessTokenUserID(at *AccessToken) uint64 {
	return at.UserID
}

// PluckAccessTokenAccessToken returns the "access_token" field value.
func PluckAccessTokenAccessToken(at *AccessToken) []byte {
	return at.AccessToken
}

// PluckAccessTokenRefreshToken returns the "refresh_token" field value.
func PluckAccessTokenRefreshToken(at *AccessToken) []byte {
	return at.RefreshToken
}

// PluckAccessTokenCreatedAt returns the "created_at" field value.
func PluckAccessTokenCreatedAt(at *AccessToken) *time.Time {
	return at.CreatedAt
}

// AccessTokens is a parsable slice of AccessToken.
type AccessTokens []*AccessToken
