-- Create "users" table
CREATE TABLE `users` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `deleted_at` timestamp NULL, `username` varchar(255) NOT NULL, `email` varchar(255) NULL, `password` varchar(255) NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), UNIQUE INDEX `email` (`email`), UNIQUE INDEX `username` (`username`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "access_tokens" table
CREATE TABLE `access_tokens` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `user_id` bigint unsigned NOT NULL, `token` binary(32) NOT NULL, `created_at` timestamp NULL, `user_access_tokens` bigint unsigned NULL, PRIMARY KEY (`id`), INDEX `access_tokens_users_access_tokens` (`user_access_tokens`), UNIQUE INDEX `token` (`token`), CONSTRAINT `access_tokens_users_access_tokens` FOREIGN KEY (`user_access_tokens`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "personal_tokens" table
CREATE TABLE `personal_tokens` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `user_id` bigint unsigned NOT NULL, `description` varchar(255) NOT NULL, `token` binary(32) NOT NULL, `created_at` timestamp NULL, `user_personal_tokens` bigint unsigned NULL, PRIMARY KEY (`id`), INDEX `personal_tokens_users_personal_tokens` (`user_personal_tokens`), UNIQUE INDEX `token` (`token`), CONSTRAINT `personal_tokens_users_personal_tokens` FOREIGN KEY (`user_personal_tokens`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "refresh_tokens" table
CREATE TABLE `refresh_tokens` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `user_id` bigint unsigned NOT NULL, `token` binary(32) NOT NULL, `created_at` timestamp NULL, `user_refresh_tokens` bigint unsigned NULL, PRIMARY KEY (`id`), INDEX `refresh_tokens_users_refresh_tokens` (`user_refresh_tokens`), UNIQUE INDEX `token` (`token`), CONSTRAINT `refresh_tokens_users_refresh_tokens` FOREIGN KEY (`user_refresh_tokens`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "permissions" table
CREATE TABLE `permissions` (`id` int unsigned NOT NULL AUTO_INCREMENT, `deleted_at` timestamp NULL, `name` varchar(255) NOT NULL, `description` varchar(255) NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), UNIQUE INDEX `name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "roles" table
CREATE TABLE `roles` (`id` int unsigned NOT NULL AUTO_INCREMENT, `deleted_at` timestamp NULL, `name` varchar(255) NOT NULL, `description` varchar(255) NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), UNIQUE INDEX `name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "role_permissions" table
CREATE TABLE `role_permissions` (`role_id` int unsigned NOT NULL, `permission_id` int unsigned NOT NULL, PRIMARY KEY (`role_id`, `permission_id`), INDEX `role_permissions_permission_id` (`permission_id`), CONSTRAINT `role_permissions_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `role_permissions_role_id` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "role_users" table
CREATE TABLE `role_users` (`role_id` int unsigned NOT NULL, `user_id` bigint unsigned NOT NULL, PRIMARY KEY (`role_id`, `user_id`), INDEX `role_users_user_id` (`user_id`), CONSTRAINT `role_users_role_id` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `role_users_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
