// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccessToken is the predicate function for accesstoken builders.
type AccessToken func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// PersonalToken is the predicate function for personaltoken builders.
type PersonalToken func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
